#!/usr/bin/env python3
"""Generate a ROM symbol map for the FreeInk emulator from ESP-IDF's linker scripts.

The emulator does not execute ESP32 mask ROM: it intercepts calls into ROM
address space and runs a native implementation instead (see Rom.cpp). To do
that it has to know which routine lives at which address, and that mapping is
published by Espressif as the `*.rom.ld` scripts in ESP-IDF. Those scripts are
addresses and names — no ROM code — so the generated map ships in the repo and
the emulator needs no blob.

    # from a local ESP-IDF checkout
    ./import-rom-symbols.py --chip esp32c3 --idf ~/esp/esp-idf

    # or straight from the published scripts
    ./import-rom-symbols.py --chip esp32c3 --ref v5.5

Regenerate a map when the emulator meets an unimplemented ROM address from a
chip revision the current map does not cover; `freeink-sim` prints the address
and the chip when that happens.
"""

import argparse
import os
import re
import sys
import urllib.request

# Bluetooth controller ROM is large, versioned, and never HLE'd — the emulator
# refuses BT calls rather than pretending. Leaving these out keeps the map to
# the symbols that actually matter for boot and peripherals.
SKIP = ("ble_", "bt_funcs")

ASSIGN = re.compile(r"^\s*(?:PROVIDE\s*\(\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+)\s*\)?\s*;")
ALIAS = re.compile(r"^\s*(?:PROVIDE\s*\(\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)?\s*;")

GITHUB = "https://api.github.com/repos/espressif/esp-idf/contents/components/esp_rom/{chip}/ld?ref={ref}"
RAW = "https://raw.githubusercontent.com/espressif/esp-idf/{ref}/components/esp_rom/{chip}/ld/{name}"


def scripts_from_idf(idf, chip):
    directory = os.path.join(idf, "components", "esp_rom", chip, "ld")
    if not os.path.isdir(directory):
        sys.exit(f"no ROM linker scripts at {directory} — is --idf an ESP-IDF checkout?")
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".ld") or any(s in name for s in SKIP):
            continue
        with open(os.path.join(directory, name), encoding="utf-8", errors="replace") as handle:
            yield name, handle.read()


def scripts_from_github(chip, ref):
    import json
    listing = json.load(urllib.request.urlopen(GITHUB.format(chip=chip, ref=ref), timeout=30))
    for entry in sorted(listing, key=lambda e: e["name"]):
        name = entry["name"]
        if not name.endswith(".ld") or any(s in name for s in SKIP):
            continue
        url = RAW.format(ref=ref, chip=chip, name=name)
        yield name, urllib.request.urlopen(url, timeout=30).read().decode("utf-8", "replace")


def parse(sources):
    """Returns {name: address}. Aliases (`esp_rom_printf = ets_printf`) resolve
    after every direct assignment is known, since a script may alias forward."""
    direct, aliases, files = {}, {}, []
    for name, text in sources:
        files.append(name)
        for line in text.splitlines():
            match = ASSIGN.match(line)
            if match:
                direct[match.group(1)] = int(match.group(2), 16)
                continue
            match = ALIAS.match(line)
            if match and match.group(1) != match.group(2):
                aliases[match.group(1)] = match.group(2)

    for name, target in aliases.items():
        seen = set()
        while target in aliases and target not in seen:
            seen.add(target)
            target = aliases[target]
        if target in direct:
            direct.setdefault(name, direct[target])
    return direct, files


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--chip", required=True, help="esp32c3, esp32s3, …")
    parser.add_argument("--idf", help="path to an ESP-IDF checkout (default: fetch published scripts)")
    parser.add_argument("--ref", default="v5.5", help="ESP-IDF git ref when fetching (default: v5.5)")
    parser.add_argument("--out", help="output path (default: <chip>.romsyms beside this script)")
    args = parser.parse_args()

    sources = scripts_from_idf(args.idf, args.chip) if args.idf else scripts_from_github(args.chip, args.ref)
    symbols, files = parse(sources)
    if not symbols:
        sys.exit(f"no ROM symbols found for {args.chip}")

    out = args.out or os.path.join(os.path.dirname(os.path.abspath(__file__)), f"{args.chip}.romsyms")
    origin = args.idf if args.idf else f"esp-idf {args.ref} (fetched)"
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(f"# ESP32 ROM symbol map for {args.chip} — addresses only, no ROM code.\n")
        handle.write(f"# Generated by import-rom-symbols.py from {origin}.\n")
        handle.write(f"# Source: components/esp_rom/{args.chip}/ld/*.ld (Apache-2.0, Espressif Systems).\n")
        handle.write(f"# {len(symbols)} symbols from {len(files)} scripts. Do not edit by hand.\n")
        for name, addr in sorted(symbols.items(), key=lambda kv: (kv[1], kv[0])):
            handle.write(f"{addr:08x} {name}\n")
    print(f"{out}: {len(symbols)} symbols from {len(files)} linker scripts")


if __name__ == "__main__":
    main()
